#!/usr/bin/env bash
echo -e "######\n#Installing Powershell ISE Linux...\n######"
echo "Checking if Powershell is installed..."
dpkg -l powershell > /dev/null 2>&1
if [ $? -eq 1 ]
then
	echo -e "Powershell not installed.\nInstalling Powershell..."
	echo "Commands used from: https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-linux?view=powershell-6"
	echo "Downloading Microsoft GPG keys..."
	wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb > /dev/null 2>&1
	echo "Install keys..."
	sudo dpkg -i packages-microsoft-prod.deb > /dev/null 2>&1
	echo "Updating apt sources..."
	sudo apt-get update > /dev/null 2>&1
	echo "Enabling \"universe\" repository..."
	sudo add-apt-repository universe > /dev/null 2>&1
	echo "Installing powershell package..."
	sudo apt-get install -y powershell > /dev/null 2>&1
else
	echo "Powershell installed."
fi
